title: Pre-Fortress 2 - RSS Feed
email: staff@prefortress.com
description: >- # this means to ignore newlines until "baseurl:"
  Pre-Fortress 2 is a mod for Team Fortress 2 that brings back grenades, armor and much more! 
  It aims to bridge the gap between Team Fortress installments and the art-style is heavily inspired by the pre-release era of Team Fortress 2! 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://prefortress.com" # the base hostname & protocol for your site, e.g. http://example.com
discord-invite: "https://prefortress.com/discord"
gameversion: "073" # current game version

# Google Analytics
google_analytics: G-Q8T3T3HDGV

# Build settings
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

feed:
  categories: 
    - updates
    - blog  

  posts_limit: 100